Выполнение задания 11
Dezmonoid/Android_Intern pull request #10
Opened 2023-06-29 17:06 UTC by Dezmonoid

2023-06-29 17:07 UTC, Dezmonoid commented
![image](https://github.com/Dezmonoid/Android_Intern/assets/129031186/edb0b5b8-7318-4125-bb09-f012f4b4bc8f)

2023-07-08 09:51 UTC, YanchenkOFF requested changes

2023-07-08 09:51 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/ColorsAdapter.kt
> +    val recyclerText: TextView = view.findViewById(R.id.text_view)
почему торчит из класса?
Сделай метод bind, который примет два параметра (Цвет и коллбэк)

2023-07-08 09:51 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/ColorsAdapter.kt
> +        holder.recyclerText.setOnClickListener { callback(colors[position]) }
передать в метод bind

2023-07-08 09:51 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        )
вынеси colorData в отдельный файл - объект

2023-08-07 17:35 UTC, YanchenkOFF requested changes

2023-08-07 17:35 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/ColorsAdapter.kt
> +        holder.bind(colors, callback)
Зачем в bind передавать весь список? достаточно просто названия цвета

2023-08-07 17:35 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            ColorsAdapter(colorsList) { Toast.makeText(this, it, Toast.LENGTH_SHORT).show() }
Лямбду не пиши в одну строку, плохо читается.
т.е. тоаст с новой строки и автоформатирование

2023-08-25 19:34 UTC, YanchenkOFF approved these changes

2023-08-25 20:10 UTC, closed without merging