Выполнение задания 12
Dezmonoid/Android_Intern pull request #11
Opened 2023-06-29 17:21 UTC by Dezmonoid

2023-06-29 17:21 UTC, Dezmonoid commented
![image](https://github.com/Dezmonoid/Android_Intern/assets/129031186/f2dcc59a-6709-4468-9a48-f535440e8dc7)

2023-07-08 09:56 UTC, YanchenkOFF requested changes

2023-07-08 09:56 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        }
а если отключить интернет на телефоне, что будет?
И где ты закрываешь соединение?

2023-08-07 17:36 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            } catch (e: Exception) {
Лучше перехватывать Throwable

2023-08-07 17:37 UTC, YanchenkOFF approved these changes

2023-08-07 20:26 UTC, closed without merging