Выполнение задания 14
Dezmonoid/Android_Intern pull request #13
Opened 2023-07-06 18:20 UTC by Dezmonoid

2023-07-08 10:14 UTC, YanchenkOFF requested changes

2023-07-08 10:14 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        binding.button.setOnClickListener { binding.tv.text = "Добрейший вечерочек" }
строку в ресурсы

2023-08-07 17:42 UTC, YanchenkOFF approved these changes

2023-08-07 17:44 UTC, YanchenkOFF requested changes

2023-08-07 17:44 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +private lateinit var binding: ActivityMainBinding
перенести внутрь активити, это должно быть полем класса

2023-08-08 05:14 UTC, Dezmonoid commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +private lateinit var binding: ActivityMainBinding
Виноват, слишком далеко выкинул.

2023-08-25 19:35 UTC, YanchenkOFF approved these changes

2023-08-25 20:10 UTC, closed without merging