Выполнение задания 15
Dezmonoid/Android_Intern pull request #14
Opened 2023-07-06 18:57 UTC by Dezmonoid

![image](https://github.com/Dezmonoid/Android_Intern/assets/129031186/52069a18-ac62-4e85-9453-fe0a2e8a93b5)

2023-07-08 10:17 UTC, YanchenkOFF requested changes

2023-07-08 10:17 UTC, YanchenkOFF commented on app/src/main/res/layout/activity_main.xml
> +        android:onClick="nextActivity"
убрать, это не очевидно. Листенеры вешать кодом в активити

2023-07-08 10:17 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +    fun nextActivity(view: View) {
Плохое название

2023-08-07 17:46 UTC, YanchenkOFF requested changes

2023-08-07 17:46 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/FullScreenActivity.kt
> +private const val ImageURL = "https://bigpicture.ru/wp-content/uploads/2012/04/2184.jpg"
константы большими буквами через _

2023-08-07 17:46 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/FullScreenActivity.kt
> +private lateinit var binding: ActivityFullScreenBinding
в класс

2023-08-07 17:46 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +private lateinit var binding: ActivityMainBinding
в класс

2023-08-07 17:46 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        openFullScreenActivity()
вызов этого метода запустит новую активити?

2023-08-08 05:17 UTC, Dezmonoid commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        openFullScreenActivity()
Согласен не вызовет, а просто вешает листенер.

2023-08-09 19:00 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        openFullScreenActivity()
Дай нормальное название

2023-08-25 19:36 UTC, YanchenkOFF approved these changes

2023-08-25 20:10 UTC, closed without merging