Выполнение задания 17
Dezmonoid/Android_Intern pull request #16
Opened 2023-07-19 16:15 UTC by Dezmonoid

https://drive.google.com/file/d/1cv5p9VqTqga5CXEZEUFjGg3nHzzVGcQc/view?usp=sharing

2023-07-22 21:45 UTC, sergfirago requested changes

2023-07-22 21:45 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        val json = """[{
Вынеси json за класс в константу. Дай подходящее название

2023-07-22 21:45 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        }
сделать рефакторинг

1. вынести в функцию
2. старайся размещать рядом определение, инициализацию  и использование переменной

2023-07-22 21:45 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/PhoneAdapter.kt
> +    class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
дать нормальное название и вынести отдельным классом

2023-08-09 19:05 UTC, YanchenkOFF requested changes

2023-08-09 19:05 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        initButtonListener()
плохое название

2023-08-09 19:05 UTC, YanchenkOFF commented on app/src/main/res/layout/phone_item.xml
> +        android:text=""
зачем устанавливать пустую строку?

2023-08-25 19:44 UTC, YanchenkOFF requested changes

2023-08-25 19:44 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        binding.recyclerViewPhone.hasFixedSize()
это зачем?

2023-08-25 19:44 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        fillRecyclerViewFilter()
плохое название

2023-09-11 08:26 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        fillRecyclerViewFilter()
Исправь тут замечания

2023-09-12 18:56 UTC, YanchenkOFF approved these changes

2023-09-12 19:02 UTC, closed without merging