Задание 18
Dezmonoid/Android_Intern pull request #17
Opened 2023-07-19 16:23 UTC by Dezmonoid

https://drive.google.com/file/d/19k8xLbPK7jWpuAlZQGnfPWalddpBpedL/view?usp=sharing

2023-07-22 21:48 UTC, sergfirago requested changes

2023-07-22 21:48 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        val jsonImageList = mutableListOf<String>()
плохое название не отображающее смысл переменной

2023-08-09 19:23 UTC, YanchenkOFF requested changes

2023-08-09 19:23 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/ImgaeAdapter.kt
> +    private val context: Context
убрать контекст

2023-08-09 19:23 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/ImgaeAdapter.kt
> +        Glide
в bind

2023-08-09 19:23 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/ImgaeAdapter.kt
> +    val imageView: ImageView = view.findViewById(R.id.image_icon)
private
и используй binding

2023-08-09 19:23 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        .build()
сделай его lateinit и инициализируй позже

2023-08-09 19:23 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +                }
просто создай новый список используя оператор map

2023-08-09 19:23 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        binding.recyclerView.layoutManager = GridLayoutManager(this, 2)
2 - что это? в константу

2023-08-09 19:23 UTC, YanchenkOFF commented on app/src/main/res/menu/full_image_menu.xml
> +        android:title=""
?

2023-08-09 19:23 UTC, YanchenkOFF commented on app/src/main/res/menu/full_image_menu.xml
> +        android:title=""
Видео работы прикрепи

2023-08-29 17:45 UTC, YanchenkOFF requested changes

2023-08-29 17:45 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        editBinding()
убери этот метод, он вводит в заблуждение

2023-08-29 17:45 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        buildAndCallUrl()
плохое название

2023-08-29 17:45 UTC, YanchenkOFF commented on app/src/main/res/menu/full_image_menu.xml
> +        android:title=""
Отмечай замечания которые исправил галочкой.

2023-09-11 08:28 UTC, YanchenkOFF requested changes

2023-09-11 08:28 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        startActivity(intent)
в метод

2023-09-11 08:28 UTC, YanchenkOFF commented on app/src/main/res/menu/full_image_menu.xml
> +        android:title=""
убери title. он тут не нужен

2023-09-12 19:03 UTC, YanchenkOFF approved these changes

2023-09-12 19:06 UTC, closed without merging