Task19
Dezmonoid/Android_Intern pull request #18
Opened 2023-07-19 17:01 UTC by Dezmonoid

https://drive.google.com/file/d/1jGt6CP-c28r0Zth34ZklGG07gPusqdpl/view?usp=sharing

2023-07-22 21:54 UTC, sergfirago requested changes

2023-07-22 21:54 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/FullImageActivity.kt
> +        intent.putExtra("result", "Like")
в константы

2023-07-22 21:54 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +                    "Картинка поместилась в избранное!",
в ресурсы

2023-07-22 21:54 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/FullImageActivity.kt
> +        intent.putExtra("result", "Like")
зачем это?

2023-07-22 21:54 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/ImgaeAdapter.kt
> +    private val context: Context
не нужно передавать контекст

2023-07-22 21:54 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/ImgaeAdapter.kt
> +            (context as Activity).startActivityForResult(intent, 1)
сделать это через лямбду

2023-07-22 21:54 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        val jsonImageList = mutableListOf<String>()
название

2023-07-22 21:54 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +                        .fromJson(response.body!!.string(), Photo::class.java)
Сделай через Gson()

2023-08-29 17:47 UTC, YanchenkOFF requested changes

2023-08-29 17:47 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
>  package com.example.android_intern
Все замечания из предыдущего задания

2023-09-11 08:32 UTC, YanchenkOFF requested changes

2023-09-11 08:32 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/FullImageActivity.kt
> +        const val TAG = "Result"
плохое название, где должна быть эта константа? Кому отправляется резудьтат?

2023-09-11 08:32 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/FullImageActivity.kt
> +        const val VALUE = "Favorite"
аналогично

2023-09-11 08:32 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        startActivityForResult(intent, 1)
в метод

2023-09-11 08:32 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            ).show()
а если с этим ключем другой экран отправит результат? Где проверка на успешный результат?
У тебя приходят requestCode и resultCode, подумай, как можно идентифицировать твой результат?

2023-09-12 19:34 UTC, YanchenkOFF approved these changes

2023-09-12 19:34 UTC, closed without merging