Задание 27
Dezmonoid/Android_Intern pull request #26
Opened 2023-08-22 17:00 UTC by Dezmonoid

2023-09-20 19:36 UTC, YanchenkOFF requested changes

2023-09-20 19:36 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        Log.d(TAG, (WeatherStore.get() == null).toString())
?

2023-09-20 19:36 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        }
в метод

2023-09-20 19:36 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        }
и рефакторинг, сделай более красиво

2023-09-20 19:36 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/WeatherStore.kt
> +    private var weathers: ForecastResponse? = null
тебе точно всю структуру нужно хранить?

2023-09-27 18:37 UTC, Dezmonoid commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        Log.d(TAG, (WeatherStore.get() == null).toString())
Забей) для себя делал и забыл снести.

2023-10-20 19:32 UTC, YanchenkOFF requested changes

2023-10-20 19:32 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            setWeatherRecyclerView()
название плохое

2023-10-20 19:32 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            setWeather()
и тут, тут что не в ресайклер сетишь? Названия вообще жесть

2023-10-20 19:32 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/WeatherStore.kt
> +    private var weathers: List<ForecastResponse.Sky?>? = null
убери нулабельность, инициализируй пустым списком

2023-10-20 19:32 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/WeatherStore.kt
> +    fun set(value: List<ForecastResponse.Sky>?) {
убрать нулабельность

2023-10-23 13:17 UTC, YanchenkOFF requested changes

2023-10-23 13:17 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +    private fun firstLoad(callback: (List<ForecastResponse.Sky>) -> Unit) {
не нужен колбэк

2023-10-23 13:17 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            saveLoad()
?

2023-12-03 10:43 UTC, YanchenkOFF requested changes

2023-12-03 10:43 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            firstLoad()
плохое название

2023-12-03 10:43 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            loadingSaveWeather()
тоже плохое название

2023-12-08 16:05 UTC, YanchenkOFF approved these changes

2023-12-08 18:04 UTC, closed without merging