Задание 28
Dezmonoid/Android_Intern pull request #27
Opened 2023-09-09 15:14 UTC by Dezmonoid

2023-09-20 19:39 UTC, YanchenkOFF requested changes

2023-09-20 19:39 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +
убрать из активити

2023-09-20 19:39 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/PhoneAdapter.kt
> +class PhoneAdapter :
убрать кликлистенер интерфейс и сделать через лямбду

2023-09-20 19:39 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/PhoneFragment.kt
> +        var phoneAdapter = PhoneAdapter()
почему адаптер в компаньене?

2023-09-20 19:39 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/PhoneFragment.kt
> +    private lateinit var binding: FragmentPhoneBinding
сделать биндинг по документации

2023-09-20 19:39 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/PhoneFragment.kt
> +        callSelectedNumber()
убрать

2023-09-20 19:39 UTC, YanchenkOFF commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/fragment_phone"
плохое ид для контейнера

2023-10-20 19:35 UTC, YanchenkOFF requested changes

2023-10-20 19:35 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
>      }
а если перевернуть телефон и потом полистать список? Все гуд?

2023-10-20 19:35 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/PhoneFragment.kt
> +    private lateinit var binding: PhoneFragmentBinding
почитай как инициализируется binding во фрагментах

2023-10-22 09:20 UTC, Dezmonoid commented on app/src/main/java/com/example/android_intern/MainActivity.kt
>      }
Да

2023-10-23 13:18 UTC, YanchenkOFF approved these changes

2023-10-24 08:06 UTC, closed without merging