Выполнение задания 4
Dezmonoid/Android_Intern pull request #3
Opened 2023-06-17 14:57 UTC by Dezmonoid

2023-06-18 07:10 UTC, sergfirago requested changes

2023-06-18 07:10 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +                applicationContext,
достаточно контекст активити те this

2023-06-20 18:07 UTC, YanchenkOFF requested changes

2023-06-20 18:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +                "Нажата ОК",
строку в ресурсы

2023-06-23 22:06 UTC, closed without merging