Задание 32/37
Dezmonoid/Android_Intern pull request #30
Opened 2023-10-18 19:10 UTC by Dezmonoid

https://drive.google.com/file/d/1fOP8UPYpisXVSVimtAVtLjIH70MQlieb/view?usp=sharing

2023-12-03 11:07 UTC, YanchenkOFF requested changes

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/App.kt
> +        apiService = RickAndMortyApi.initApiService()
вынеси в ф-ю

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/Episode.kt
> +class Episode : ArrayList<Episode.EpisodeItem>(){
почему класс и arrayList?

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        changeFragment(CharacterFragment())
название очень плохое

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        changeFragment(CharacterFragment())
Ты понимаешь, то при переворотах у тебя всегда вызывается твой метод?

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/RickAndMortyApi.kt
> +        fun initApiService(): RickAndMortyApi {
название плохое

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/RickAndMortyApi.kt
> +        fun initApiService(): RickAndMortyApi {
посмотри из места вызова этого метода, какое название больше подходит? и что делает твой метод?

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/Character.kt
> +data class Character(
Characters

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/fragment/EpisodeFragment.kt
> +class EpisodeFragment(private var episode: String) : Fragment() {
получение данных вынести во viewModel

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/fragment/EpisodeFragment.kt
> +class EpisodeFragment(private var episode: String) : Fragment() {
И обязательно почитать про конструкторы фрагментов и понять как передавать параметры во фрагмент

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/RickAndMortyApi.kt
> +    fun getCharacter(): Call<Character>
getCharacters

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/Episode.kt
> +class Episode : ArrayList<Episode.EpisodeItem>(){
Episodes

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/RickAndMortyApi.kt
> +    fun getEpisode(
episodes

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/adapter/CharacterAdapter.kt
> +        this.itemView.setOnClickListener {
используй binding, что бы было однотипно

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/fragment/CharacterFragment.kt
> +const val TAG = "Debug"
private

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/fragment/CharacterFragment.kt
> +        (context as MainActivity).changeFragment(EpisodeFragment(character.episode?.map {
Как будет время, набирай будет разбираться с навигацией фрагментов чз suppotFragmentManage. Пока прочитай про него

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/fragment/CharacterFragment.kt
> +    private fun loadCharacter() {
во вьюмодель

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/fragment/EpisodeFragment.kt
> +        initCharacterRecyclerView()
episodes?

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/res/layout/activity_main.xml
>      android:layout_width="match_parent"
пересмотреть Sp И Dp

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="wrap_content" />
почему врап?

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/res/layout/character_fragment.xml
> +        android:layout_height="wrap_content"
врап?

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/res/layout/episode_fragment.xml
> +        android:layout_height="wrap_content"
врап?

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/res/values/colors.xml
> +    <color name="blue">#2653FF</color>
это нужно?

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/res/values/colors.xml
> +    <color name="blue">#2653FF</color>
Зайди в просмотр эпизодов и переверни телефон)

2023-12-03 11:07 UTC, YanchenkOFF commented on app/src/main/res/values/colors.xml
> +    <color name="blue">#2653FF</color>
что будет?

2023-12-11 15:27 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/Episodes.kt
> +class Episodes : ArrayList<Episodes.EpisodeItem>(){
??? ArrayList?

2023-12-11 15:28 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/RickAndMortyApi.kt
> +    fun getEpisode(
up

2023-12-11 15:29 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/fragment/CharactersFragment.kt
> +        }?.joinToString(",", "", "") ?: ""
прочитай про значение параметров по умолчанию

2023-12-11 15:31 UTC, sergfirago commented on app/src/main/res/drawable/cold.png
убери лишние ресурсы

2024-01-28 13:45 UTC, YanchenkOFF approved these changes

2024-01-28 14:04 UTC, closed without merging