Выполнение задания 5
Dezmonoid/Android_Intern pull request #4
Opened 2023-06-17 15:42 UTC by Dezmonoid

2023-06-18 07:15 UTC, sergfirago requested changes

2023-06-18 07:15 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        val TAG = "Intern"
в константы

2023-06-18 07:15 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        Timber.plant(Timber.DebugTree())
подключи через app для всего приложения, а не только для этого экрана

2023-07-08 09:28 UTC, YanchenkOFF requested changes

2023-07-08 09:28 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainAPP.kt
> +class MainAPP:Application() {
Называй всегда App, такой нейминг будешь встречать постоянно

2023-07-08 09:28 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainAPP.kt
> +        Timber.plant(Timber.DebugTree())
Почему перед супер? И где проверка на BuildConfig?

2023-07-08 09:28 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +
пустые строки не оставляй

2023-07-08 09:28 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            Log.i("Task5", "projectInfo")
Зачем использовать Log, это есть в задании?

2023-07-08 10:24 UTC, Dezmonoid commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            Log.i("Task5", "projectInfo")
Ну как бы изначально сказано что в лог выводить текст с editа, а про тимбер сказано только подключить

2023-08-07 17:28 UTC, YanchenkOFF approved these changes

2023-08-08 04:57 UTC, closed without merging