Выполнение задания 7
Dezmonoid/Android_Intern pull request #6
Opened 2023-06-17 16:46 UTC by Dezmonoid

2023-06-18 07:19 UTC, sergfirago requested changes

2023-06-18 07:19 UTC, sergfirago commented on app/src/main/res/layout/activity_main.xml
> +    </androidx.constraintlayout.widget.ConstraintLayout>
ошибка. перечитай тему

2023-06-28 18:49 UTC, Dezmonoid commented
![image](https://github.com/Dezmonoid/Android_Intern/assets/129031186/297f88ea-7443-4375-bcae-d44d78bc7d75)

2023-07-08 09:29 UTC, YanchenkOFF approved these changes

2023-07-08 10:25 UTC, closed without merging