Выполнение задания 8
Dezmonoid/Android_Intern pull request #7
Opened 2023-06-17 16:54 UTC by Dezmonoid

2023-06-18 07:21 UTC, sergfirago requested changes

2023-06-18 07:21 UTC, sergfirago commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +            textView.text = "Нажата кнопка"
текст в ресурсы

2023-06-20 18:09 UTC, YanchenkOFF requested changes

2023-06-20 18:09 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +    @SuppressLint("MissingInflatedId")
Это зачем?

2023-06-21 04:58 UTC, Dezmonoid commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +    @SuppressLint("MissingInflatedId")
Сама андроид студия предлагает добавить когда я по id ищу элементы интерфейса

2023-06-23 18:21 UTC, YanchenkOFF approved these changes

2023-06-23 22:07 UTC, closed without merging