Выполнение задания 9
Dezmonoid/Android_Intern pull request #8
Opened 2023-06-20 16:12 UTC by Dezmonoid

2023-06-20 18:11 UTC, YanchenkOFF requested changes

2023-06-26 13:37 UTC, Dezmonoid commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +    @SuppressLint("MissingInflatedId")
Котлин сказал так сделать)

2023-06-28 19:00 UTC, Dezmonoid commented
![image](https://github.com/Dezmonoid/Android_Intern/assets/129031186/543d4c78-3a73-4c38-95a7-bd8838801065)

2023-07-08 09:42 UTC, YanchenkOFF approved these changes

2023-07-08 10:20 UTC, closed without merging