Выполнение задания 10
Dezmonoid/Android_Intern pull request #9
Opened 2023-06-22 18:44 UTC by Dezmonoid

2023-06-23 18:25 UTC, YanchenkOFF requested changes

2023-06-23 18:25 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +class RecyclerAdapter(private val colorData: List<String>) :
вынеси класс в отдельный файл

2023-06-23 18:25 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +    class RecyclerHolder(textView: View) : RecyclerView.ViewHolder(textView) {
Плохое класса название вьюхолдера. И вынеси его лучше за класс. (в файле адаптера, но за пределами класса)

2023-06-23 18:25 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        var recyclerText: TextView = textView.findViewById(R.id.text_view)
изменяемое свойство торчит из класса

2023-06-23 18:25 UTC, YanchenkOFF commented on app/src/main/res/layout/recyclerview_item.xml
> +        android:textSize="32dp" />
размер текста указывается в sp

2023-06-26 13:35 UTC, Dezmonoid commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +        var recyclerText: TextView = textView.findViewById(R.id.text_view)
Тут немного не понял

2023-07-08 09:45 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +
не оставляй лишние пустые строки

2023-07-08 09:45 UTC, YanchenkOFF commented on app/src/main/java/com/example/android_intern/MainActivity.kt
> +
Где скриншот?

2023-07-08 09:46 UTC, YanchenkOFF approved these changes

2023-07-08 10:20 UTC, closed without merging